### ISSUE TITLE
Add Java to Role dependencies and/or documentation

### ISSUE THREAD

**Issue by timblaktu** [wcm-io-devops/ansible-jenkins-pipeline-library#24]
I am replacing a section of my `jenkins.yml` playbook, which was using `geerlingguy.jenkins`, with this role. I noticed that you are not including java anywhere in your dependencies or documentation. You might want to add java to your Dependencies documentation or perhaps to [the role dependencies list in meta](https://github.com/wcm-io-devops/ansible-jenkins-pipeline-library/blob/master/meta/main.yml#L20) . 

As you probably know, `geerlingguy.jenkins` doesn't install java, which is a prerequisite for it. So I e.g. am using `geerlingguy.java` role to install java, and am invoking it from my``jenkins.yml` before `wcm_io_devops.jenkins_pipeline_library`. My requirements file now looks like this:

```
- name: geerlingguy.java
  version: 1.10.0                                                                                                                                                                            - name: geerlingguy.docker
  version: 2.8.1
# This is now installed as a dependency of wcm_io_devops.jenkins_pipeline_library. No need to include here.
# - name: geerlingguy.jenkins
#   version: 4.3.0
- name: wcm_io_devops.jenkins_pipeline_library
  version: 2.222.3-1
```

**Comment by tobias-richter** [comment]
@timblaktu we had a java dependency some time ago and it caused some problems so the user has to decide for a role and a installation method. 

I have updated the documentation containg links to recommended roles: https://github.com/wcm-io-devops/ansible-jenkins-pipeline-library/blob/master/README.md#requirements
