### ISSUE TITLE
version 2.222.3-1 failing to download jenkins .deb

### ISSUE THREAD

**Issue by timblaktu** [wcm-io-devops/ansible-jenkins-pipeline-library#25]
When I run `wcm_io_devops.jenkins_pipeline_library` version 2.222.3-1, with `jenkins_pipeline_library_jenkins_install: true` I get an error downloading the .deb bc that file version doesn't exist:

```
TASK [geerlingguy.jenkins : Download specific Jenkins version.] *****************************************************************************************************************************fatal: [jmtest3]: FAILED! => changed=false
  dest: /tmp/jenkins_2.222.3_all.deb
  elapsed: 0
  msg: Request failed
  response: 'HTTP Error 404: The specified blob does not exist.'
  status_code: 404
  url: https://pkg.jenkins.io/debian/binary/jenkins_2.222.3_all.deb
```

I confirmed that this blob doesn't exist in a browser. Also, this file appears to exist on other debian-stable package mirrors like [this one](http://mirror.math.princeton.edu/pub/jenkins/debian-stable/), so perhaps this is just a mirroring issue.

I don't think this is related, but my jenkins-master being provisioned is a Debian Buster machine, and I noticed on your ansible galaxy role page, you only list support for Stretch. Curious about that, whether that's something I should worry about. Thanks.

**Comment by timblaktu** [comment]
This indeed appears to be an issue with the default debian site being down or not containing that version for some reason. I have created a fork and branch adding the ability to customize the jenkins_pkg_url passed to geerlingguy.jenkins and when I use `http://mirror.math.princeton.edu/pub/jenkins/debian-stable/` this error goes away. I will submit a PR for this since it seems a generally-useful thing to be able to set this inner role variable through your role.

**Comment by tobias-richter** [comment]
@timblaktu i just updated the documentation with a new sample playbook:


    - hosts: localhost
      become: yes
      vars:
        # values for geerlingguy.jenkins
        jenkins_prefer_lts: true
        # required until https://github.com/geerlingguy/ansible-role-jenkins/pull/294 is merged    
        jenkins_pkg_url: "https://pkg.jenkins.io/debian-stable/binary"
        
        # values for wcm_io_devops.jenkins_pipeline_library
        jenkins_pipeline_library_jenkins_install: true
      roles:
        - role: geerlingguy.java
        - role: wcm_io_devops.jenkins_pipeline_library

The binary is on the jenkins servers but not on the normal path. This is a known issue and there is a PR available (https://github.com/geerlingguy/ansible-role-jenkins/pull/294)
